config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'
  delete "/logout" => "user_sessions#destroy", as: :logout
  resources :users
  resources :user_sessions , only: [ :create, :new]
  resources :event_entries,  only: [:edit, :create, :new, :index]
  resources :events, only: [:show, :index]

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_entries
end

app/models/event_entry.rb
class EventEntry < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :user_id, uniqueness: { scope: :event_id, notice: "You can only register to event once"}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :event_entries
  has_many :events ,through: :event_entries
  has_secure_password
  validates :email, presence: true,
                     uniqueness: true,
                     format: {
                      with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
                     }
  before_save :downcase_email
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @curent_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def require_user
    if current_user
      true
    else
      redirect_to new_user_session_path, notice: "You must be logged in to register"
    end
  end
end

app/controllers/event_entries_controller.rb
class EventEntriesController < ApplicationController
  before_action :require_user
  def index
    @evententry = current_user.event_entries
    @event = current_user.events
  end
  def new
    @evententry = EventEntry.new
  end
  def create
    @evententry = current_user.event_entries.new(evententry_params)
      if @evententry.save
        redirect_to events_path, notice: 'Registered successfully'
      else
        render :new
      end
  end
  def edit
    @evententry = EventEntry.find(params[:id])
  end
  def evententry_params
    params.require(:event_entry).permit(:first_name, :middle_name, :last_name, :name_on_certificate, :accomodation, :paid, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:sucess] = "Signed in successfully"
      redirect_to event_entries_path
    else
       render action: 'new'
       flash[:error] = "Login Unsucessful, please check your email and/or password"
    end
    end
  def destroy
    session[:user_id] = nil
    reset_session
    redirect_to root_path, notice: "You have Signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
	session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_entries_helper.rb
module EventEntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_entries/index.html.erb
<h1>Your registrations </h1>
<div> <%= link_to "Events List", root_path%>| <%= link_to "Register to an event", new_event_entry_path%>
</div>
<% @evententry.each do |entry|%>
  <%= entry.first_name%>
  <%= entry.middle_name%>
  <%= entry.last_name%>
  </br>
  <%= entry.name_on_certificate%>
  </br>
  <% if entry.paid%>
    Paid
  <%else%>
    Payment not received
  <%end%>
  <% if entry.accomodation_request%>
    Accomodation requested
  <%else%>
    Accomodation not requested
  <%end%>
  </br>
  <%=entry.event.name%> 
  <hr>
<%end%>

app/views/event_entries/new.html.erb
<%= form_for @evententry, url: {action: "create"} do |f|%>
  <%= f.label :first_name%> <br>
  <%= f.text_field :first_name%> <br>
  <%= f.label :middle_name%> <br>
  <%= f.text_field :middle_name%> <br>
  <%= f.label :last_name%> <br>
  <%= f.text_field :last_name%> <br>
  <%= f.label :name_on_certificate%> <br>
  <%= f.text_field :name_on_certificate%> <br>
  <%= f.check_box :accomodation_request,as: :boolean, checked_value: true, unchecked_value: false%>
  <%= f.label :accomodation_request%>
  <br>
  <%= f.label :event_id, "Event"%> <br>
  <%= f.select :event_id, Event.all.collect {|x| [x.name, x.id] }%> <small>please select the required event</small> <br>
  <%= f.submit "Register"%>
<%end%>

app/views/events/index.html.erb
<h1> Listing events </h1>
<% if current_user%>
  <small> <%= link_to "Registrations", event_entries_path%> </small>
<%end%>
<% @events.each do |event|%>
  <h4> <%=event.name%> </h4>
  <small> <%= event.venue%> | <%= link_to 'More Info', event%></small>
  <hr>
<%end%>
<!-- dont forget strftime("%d-%B-%Y")-->

app/views/events/show.html.erb
<h1><%= @event.name%></h1>
<div><%= @event.description%></div>
<%= link_to "Register", new_event_entry_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |k, v|%>
    <%= content_tag :div, v, class: "flash #{k}"%>
  <%end%>
  <%if current_user%>
    <h4> currrently logged in as <%=current_user.first_name%> <%=current_user.last_name%> | <%= link_to "Sign out", logout_path, method: :delete%> </h4>
  <%else%>
    <%= link_to "Sign in", new_user_session_path%> | <%= link_to "Sign up", new_user_path%>
  <%end%>
<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<h1> Log in </h1>
<%= form_tag user_sessions_path do%>
  <%= label_tag :email, "Email Address"%>
  <%= text_field_tag :email, params[:email]%>
</br>
  <%= label_tag :password, "Password"%>
  <%= password_field_tag :password%>
</br>
  <%= submit_tag "Log in"%>
<%end%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %>
  </div>
<div class="field">
    <%= f.label :password_confirmation, "Password Confirmation"%> </br>
    <%= f.password_field :password_confirmation%>
</div>
  <div class="actions">
    <%= f.submit "Sign Up"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>